# Generated by Django 4.2.11 on 2024-04-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PastelDeNata', '0006_alter_client_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bio',
            field=models.CharField(default='Sem bio ainda...', max_length=150, null=True),
        ),
    ]
