# Generated by Django 5.0.3 on 2024-03-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0002_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='total_votos',
            field=models.IntegerField(default=0),
        ),
    ]
