# Generated by Django 5.0.3 on 2024-04-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0003_aluno_total_votos'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='avatar',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
