# Generated by Django 5.0.3 on 2024-04-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0004_aluno_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='avatar',
            field=models.CharField(default='AvatarDefault', max_length=25),
        ),
    ]
