# Generated by Django 5.0.3 on 2024-04-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0005_alter_aluno_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcao',
            name='votadores',
            field=models.ManyToManyField(to='votacao.aluno'),
        ),
    ]
