# Generated by Django 5.0.3 on 2024-04-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0006_opcao_votadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='votadores',
            field=models.ManyToManyField(related_name='votos', to='votacao.aluno'),
        ),
    ]
